/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		ElButton: (typeof import('element-plus/es'))['ElButton']
		ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
		ElMenu: (typeof import('element-plus/es'))['ElMenu']
		ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
		ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
		ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
	}
}
